services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Change to "3000:80" if port 80 is in use
    container_name: my-react-container
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:${BACKEND_PORT}
    # Remove volumes for production. Uncomment below lines for development.
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules

  backend:
    build:
      context: ./HAPI-API
      dockerfile: Dockerfile
    container_name: hapi-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      - NODE_ENV=${BACKEND_NODE_ENV}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    # Volumes are typically not needed in production. Uncomment for development.
    # volumes:
    #   - ./HAPI-API:/app
    #   - /app/node_modules

networks:
  app-network:
    driver: bridge
